name = "Veld"
grammar = "veld"
path_suffixes = ["veld"]
line_comments = ["# "]
block_comment = ["#* ", " *#"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
word_characters = ["_"]

[language_servers]
veld-lsp = {}

[formatter]
external = { command = "veld", arguments = ["fmt", "--stdin"] }

[code_actions]
on_format = []
